"""Smart notifications: deterministic, rule-based alerts computed from the
user's own real logged data (workout_logs, meal_logs) - never generated by
a model, matching this app's existing "real data only" boundary (rule 2).
Nothing is persisted; the list is recomputed fresh on every request.

Meal-skip checks look at *yesterday* rather than today: the app has no
timezone data for the user, so there's no reliable way to know whether
today's remaining meals still have time to be logged. Checking a day that
has fully elapsed avoids flagging a meal the user simply hasn't gotten to
yet. Today's protein check instead uses "so far" language, which stays
true regardless of what time it is.

"Today" here is the server's local date (`date.today()`), matching the
same default every log_date falls back to elsewhere (workout_log_service,
meal_log_service, weekly_report_service) - using a different time
reference here (e.g. UTC) would silently misalign with what a log actually
got dated, most visibly for users in timezones far from the server's.
"""

from datetime import date, datetime, timedelta, timezone
from decimal import Decimal

from app.models import User
from app.repositories import meal_log_repository, workout_log_repository

EXERCISE_INACTIVITY_THRESHOLD_DAYS = 3
PROTEIN_TARGET_G_PER_KG = Decimal("0.8")  # general RDA baseline (0.8g protein/kg bodyweight)
LOW_PROTEIN_RATIO = Decimal("0.7")
CORE_MEAL_TYPES = ("breakfast", "lunch", "dinner")


def _exercise_inactivity_alert(user: User, today):
    most_recent_log_date = workout_log_repository.get_most_recent_log_date(user.user_id)
    if most_recent_log_date is not None:
        days_inactive = (today - most_recent_log_date).days
    else:
        # No log_date to compare against yet - fall back to account age.
        # user.created_at is stored in UTC (see app.models.mixins.utcnow),
        # so this is computed as a UTC-to-UTC datetime difference rather
        # than mixed with the caller's local `today`, which would silently
        # drift by a day right around local midnight in timezones far from
        # the server's.
        created_at_utc = user.created_at.replace(tzinfo=timezone.utc)
        days_inactive = (datetime.now(timezone.utc) - created_at_utc).days

    if days_inactive >= EXERCISE_INACTIVITY_THRESHOLD_DAYS:
        return {
            "type": "exercise_inactivity",
            "severity": "warning",
            "message": (
                f"You haven't exercised for {days_inactive} days. "
                "Log a workout to get back on track."
            ),
        }
    return None


def _skipped_meal_alerts(user: User, today):
    if not meal_log_repository.has_any_logs(user.user_id):
        return []

    yesterday = today - timedelta(days=1)
    logged_types = meal_log_repository.get_meal_types_for_date(user.user_id, yesterday)

    return [
        {
            "type": "skipped_meal",
            "severity": "info",
            "message": f"You skipped {meal_type} yesterday.",
        }
        for meal_type in CORE_MEAL_TYPES
        if meal_type not in logged_types
    ]


def _low_protein_alert(user: User, today):
    if user.weight_kg is None:
        return None

    todays_logs = meal_log_repository.get_for_date(user.user_id, today)
    if not todays_logs:
        return None

    total_protein = sum((log.protein_g for log in todays_logs), Decimal("0"))
    target = (user.weight_kg * PROTEIN_TARGET_G_PER_KG).quantize(Decimal("1"))

    if total_protein < target * LOW_PROTEIN_RATIO:
        return {
            "type": "low_protein",
            "severity": "info",
            "message": (
                f"Today's protein intake is low so far ({total_protein}g of your "
                f"~{target}g target based on your weight)."
            ),
        }
    return None


def get_notifications(user: User) -> list[dict]:
    today = date.today()
    alerts = []

    exercise_alert = _exercise_inactivity_alert(user, today)
    if exercise_alert:
        alerts.append(exercise_alert)

    alerts.extend(_skipped_meal_alerts(user, today))

    protein_alert = _low_protein_alert(user, today)
    if protein_alert:
        alerts.append(protein_alert)

    return alerts
