"""Initial schema: users, reference tables, plans, foods, analysis, recommendations, ai_model_files

Revision ID: 1f8f38eaa060
Revises: 
Create Date: 2026-07-16 17:58:55.896674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8f38eaa060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_groups',
    sa.Column('age_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('age_group_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_model_files',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('trained_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('bmi_categories',
    sa.Column('bmi_category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('min_bmi', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('max_bmi', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.PrimaryKeyConstraint('bmi_category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('body_type_categories',
    sa.Column('body_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('body_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sri_lankan_foods',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vitamins', sa.String(length=255), nullable=True),
    sa.Column('minerals', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('image_analysis_records',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('predicted_body_type_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['predicted_body_type_id'], ['body_type_categories.body_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('meal_plans',
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('body_type_id', sa.Integer(), nullable=False),
    sa.Column('bmi_category_id', sa.Integer(), nullable=False),
    sa.Column('age_group_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('breakfast', sa.Text(), nullable=False),
    sa.Column('lunch', sa.Text(), nullable=False),
    sa.Column('dinner', sa.Text(), nullable=False),
    sa.Column('snacks', sa.Text(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vitamins', sa.String(length=255), nullable=True),
    sa.Column('minerals', sa.String(length=255), nullable=True),
    sa.Column('daily_water_ml', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_groups.age_group_id'], ),
    sa.ForeignKeyConstraint(['bmi_category_id'], ['bmi_categories.bmi_category_id'], ),
    sa.ForeignKeyConstraint(['body_type_id'], ['body_type_categories.body_type_id'], ),
    sa.PrimaryKeyConstraint('meal_plan_id'),
    sa.UniqueConstraint('body_type_id', 'bmi_category_id', 'age_group_id', 'gender', name='uq_meal_plan_lookup'),
    sa.UniqueConstraint('plan_code')
    )
    op.create_table('workout_plans',
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('body_type_id', sa.Integer(), nullable=False),
    sa.Column('bmi_category_id', sa.Integer(), nullable=False),
    sa.Column('age_group_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('warm_up', sa.Text(), nullable=False),
    sa.Column('cardio', sa.Text(), nullable=False),
    sa.Column('strength_training', sa.Text(), nullable=False),
    sa.Column('stretching', sa.Text(), nullable=False),
    sa.Column('cool_down', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.String(length=100), nullable=True),
    sa.Column('weekly_schedule', sa.String(length=255), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_groups.age_group_id'], ),
    sa.ForeignKeyConstraint(['bmi_category_id'], ['bmi_categories.bmi_category_id'], ),
    sa.ForeignKeyConstraint(['body_type_id'], ['body_type_categories.body_type_id'], ),
    sa.PrimaryKeyConstraint('workout_plan_id'),
    sa.UniqueConstraint('body_type_id', 'bmi_category_id', 'age_group_id', 'gender', name='uq_workout_plan_lookup'),
    sa.UniqueConstraint('plan_code')
    )
    op.create_table('user_recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('bmi_value', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['image_analysis_records.analysis_id'], ),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.meal_plan_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.workout_plan_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recommendations')
    op.drop_table('workout_plans')
    op.drop_table('meal_plans')
    op.drop_table('image_analysis_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sri_lankan_foods')
    op.drop_table('body_type_categories')
    op.drop_table('bmi_categories')
    op.drop_table('ai_model_files')
    op.drop_table('age_groups')
    # ### end Alembic commands ###
