"""Add serving_size to sri_lankan_foods

Revision ID: 75dffec41e61
Revises: cc1fb4a9af40
Create Date: 2026-07-20 12:57:39.419705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75dffec41e61'
down_revision = 'cc1fb4a9af40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sri_lankan_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serving_size', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sri_lankan_foods', schema=None) as batch_op:
        batch_op.drop_column('serving_size')

    # ### end Alembic commands ###
