"""add meal_logs table

Revision ID: 898b5dff5cbc
Revises: 6fc9a27eaeed
Create Date: 2026-08-09 20:46:15.980023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898b5dff5cbc'
down_revision = '6fc9a27eaeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('quantity_servings', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['sri_lankan_foods.food_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_logs')
    # ### end Alembic commands ###
