"""Add ML recommendation record tables and matched_person_id

Revision ID: cc1fb4a9af40
Revises: 1f8f38eaa060
Create Date: 2026-07-20 11:06:03.194856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc1fb4a9af40'
down_revision = '1f8f38eaa060'
branch_labels = None
depends_on = None


_ENGINE_TABLES = [
    "age_groups",
    "ai_model_files",
    "bmi_categories",
    "body_type_categories",
    "image_analysis_records",
    "meal_plans",
    "sri_lankan_foods",
    "user_recommendations",
    "users",
    "workout_plans",
]


def upgrade():
    # Pre-existing tables were silently created on MyISAM (this MySQL
    # server's default_storage_engine), which ignores FOREIGN KEY clauses
    # and has no transaction support - the FKs declared on the models
    # since Module 2 were never actually enforced. Convert everything to
    # InnoDB first so the FK constraints added below (and the new Module
    # 11 tables) actually take effect.
    for table in _ENGINE_TABLES:
        op.execute(f"ALTER TABLE {table} ENGINE=InnoDB")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_recommendation_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('bmi', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('bmi_category', sa.String(length=20), nullable=False),
    sa.Column('breakfast', sa.String(length=255), nullable=False),
    sa.Column('morning_snack', sa.String(length=255), nullable=False),
    sa.Column('lunch', sa.String(length=255), nullable=False),
    sa.Column('evening_snack', sa.String(length=255), nullable=False),
    sa.Column('dinner', sa.String(length=255), nullable=False),
    sa.Column('daily_calories', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('record_id'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('meal_recommendation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_recommendation_records_person_id'), ['person_id'], unique=True)

    op.create_table('workout_recommendation_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('fitness_level', sa.String(length=20), nullable=False),
    sa.Column('workout_type', sa.String(length=50), nullable=False),
    sa.Column('workout_category', sa.String(length=50), nullable=False),
    sa.Column('intensity', sa.String(length=20), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=False),
    sa.Column('target_muscle', sa.String(length=50), nullable=False),
    sa.Column('equipment', sa.String(length=50), nullable=True),
    sa.Column('indoor_outdoor', sa.String(length=20), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=False),
    sa.Column('warmup_min', sa.Integer(), nullable=False),
    sa.Column('cooldown_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['meal_recommendation_records.person_id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('workout_recommendation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_recommendation_records_person_id'), ['person_id'], unique=True)

    with op.batch_alter_table('image_analysis_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'body_type_categories', ['predicted_body_type_id'], ['body_type_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'age_groups', ['age_group_id'], ['age_group_id'])
        batch_op.create_foreign_key(None, 'body_type_categories', ['body_type_id'], ['body_type_id'])
        batch_op.create_foreign_key(None, 'bmi_categories', ['bmi_category_id'], ['bmi_category_id'])

    with op.batch_alter_table('user_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_person_id', sa.String(length=20), nullable=True))
        batch_op.alter_column('meal_plan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('workout_plan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'workout_plans', ['workout_plan_id'], ['workout_plan_id'])
        batch_op.create_foreign_key(None, 'meal_recommendation_records', ['matched_person_id'], ['person_id'])
        batch_op.create_foreign_key(None, 'meal_plans', ['meal_plan_id'], ['meal_plan_id'])
        batch_op.create_foreign_key(None, 'image_analysis_records', ['analysis_id'], ['analysis_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'age_groups', ['age_group_id'], ['age_group_id'])
        batch_op.create_foreign_key(None, 'body_type_categories', ['body_type_id'], ['body_type_id'])
        batch_op.create_foreign_key(None, 'bmi_categories', ['bmi_category_id'], ['bmi_category_id'])

    # ### end Alembic commands ###


def downgrade():
    # Storage engine conversion (MyISAM -> InnoDB) is intentionally not
    # reverted here: going back to MyISAM would silently drop the FK
    # constraints being removed below anyway, and re-introduce the
    # transaction-safety gap this migration fixed.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('workout_plan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('meal_plan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('matched_person_id')

    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('image_analysis_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('workout_recommendation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_recommendation_records_person_id'))

    op.drop_table('workout_recommendation_records')
    with op.batch_alter_table('meal_recommendation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_recommendation_records_person_id'))

    op.drop_table('meal_recommendation_records')
    # ### end Alembic commands ###
