"""Add exercises table

Revision ID: f2895c49193b
Revises: 75dffec41e61
Create Date: 2026-07-20 13:42:40.036340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2895c49193b'
down_revision = '75dffec41e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=150), nullable=False),
    sa.Column('target_muscle', sa.String(length=150), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('calories_per_30min', sa.Integer(), nullable=False),
    sa.Column('benefit', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    # ### end Alembic commands ###
